### ISSUE TITLE
Applications being submitted but not captured in responses

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#153] opened 2015-11-25 18:43 UTC
So far there have been two instances where an applicant has completed and submitted an application but the record was not created in the response sheet.

**Comment by rooneywp** [comment] 2015-11-25 18:57
Instance 1
Applicant: Kendra Howard

Original submission: 11/16 - Failed
First re-submission:  11/25 approx 9:47 pst - Failed

I sent her the direct link to the form instead of the Join Page. When she used that link the submission was successful. I also had her take a screen shot of the application:
[Kendra-Howard-App-Screenshot.pdf](https://github.com/18F/joining-18f/files/44211/Kendra-Howard-App-Screenshot.pdf)

I tried to identify what in her application could be causing the failure:

In the response sheet they are test 6, 7 and (test) Kendra Howard.
- Test 6 -  Tested her email as it is a .co
- Test 7 - Tested the links 1-3 she provided and resume link
- (test) - Submitted the application using the exact information provided

I haven't yet been able to reproduce the error.

**Comment by fureigh** [comment] 2015-11-25 18:59
@rooneywp Thanks for the bug report! Can you send me the above privately and redact the comment ASAP? I <3 working in the open but let's be careful to not share applicants' information in this public repo.

**Comment by fureigh** [comment] 2015-11-25 19:21
Looping in @xtine: 
1. Any insights?
2. As @rooneywp hasn't yet been able to reproduce the error, there's a chance applicants are thinking they've submitted the form when they actually haven't. What would you think of redirecting to a confirmation page instead of using that confirmation modal?

**Comment by fureigh** [comment] 2015-11-25 19:23
Might be overkill, but if this persists we could put a Google Analytics click handler on the submit button and compare the results against the number of applications received (since the time the click handler was added).

**Comment by xtine** [comment] 2015-11-25 21:45
I think redirecting to a confirmation page might be better than the modal for user experience. I'll be happy to create the thank you page but I would need help in what the page should say (success paragraph, maybe an e-mail contact as well for further questions?)

On the technical side however, a redirect or a modal trigger are still both events that happen after a form success callback. There are two potential cases I can think of:
A) User thinks they have submitted the form, but haven't. In this case, the success modal would not be triggered.
B) The user submits the form and success modal is triggered, but somehow it did not go through due to client side or server error. Even in the case that there is a form error that did not get caught through the front-end, it should take them to the generic Google Form error page and resubmitting the document would also take them to the generic Google Form success page.

**Comment by fureigh** [comment] 2015-11-30 18:20
@xtine Thanks! How about we start with the content that's in the current modal, plus the "If you have any questions" line from the [How to Apply](https://pages.18f.gov/joining-18f/how-to-apply/) page?

Hopefully failure to redirect to a confirmation page, if that ends up being part of the issue, will be clearer than failure to get a confirmation modal.

**Comment by fureigh** [comment] 2015-12-04 01:20
Closed in b3d6e8a/#156.

**Comment by fureigh** [comment] 2015-12-04 01:21
Rather — we think that'll address it. @rooneywp, if the problem persists, please reopen this issue. Thanks!

**Closed as completed by fureigh** 2015-12-04 01:20 UTC
Labels: bug
