### ISSUE TITLE
Email subscription may not show on-screen confirmation for everyone

### ISSUE THREAD

**Issue by JennMoran** [18F/joining-18f#286] opened 2016-07-07 20:07 UTC
Someone emailed Join18F that there is a possible bug when people try to subscribe for updates [here](https://pages.18f.gov/joining-18f/open-positions/).  

Email from person:

This may not be the right place to report a bug, but the form to subscribe to updates[1] doesn't give any feedback when you hit the "Subscribe" button.  There is content in the response[2] and I did get the email to confirm, but it would be nice to see the message after submitting the form.  The post results in a 307, which may be part of the problem.

[1] At https://pages.18f.gov/joining-18f/open-positions/
[2] From https://gsa.us9.list-manage.com/subscribe/post-json?u=6f1977de9eff4c384dc8d6527&id=a78bd73141&c=jQuery19001418647654886367_1467855155334&FNAME=[FIRSTNAME]&LNAME=[LASTNAME]&EMAIL=[EMAIL]&subscribe=Subscribe&_=1467855155335:
jQuery19001418647654886367_1467855155334({"result":"success","msg":"Almost finished... We need to confirm your email address. To complete the subscription process, please click the link in the email we just sent you."})

**Comment by fureigh** [comment] 2016-07-08 20:55
Thanks for reporting, @JennMoran! Closing this one as a duplicate of #285.

**Comment by fureigh** [comment] 2016-07-08 21:03
Upon further examination, the subscriber is successfully receiving email confirmation (hooray!). When I test subscription using Chrome 51.0.2704.103 (64-bit) on a Mac, I do see on-screen feedback:

![screen shot 2016-07-08 at 2 02 22 pm](https://cloud.githubusercontent.com/assets/1244599/16701421/833606f4-4514-11e6-9632-745bf7c36aaf.png)

@JennMoran, mind if I email the original reporter to ask what browser they're using?

**Comment by JennMoran** [comment] 2016-07-11 11:45
@fureigh yes - I will fwd you their email.  thank you!

**Comment by fureigh** [comment] 2016-07-12 23:16
Update: the person who reported this bug was using the Chrome extension [Disconnect](https://disconnect.me/), which blocked some of the Mailchimp requests.

**Closed as completed by fureigh** 2016-07-12 23:16 UTC
Labels: bug, duplicate
